# Generated by Django 4.0.3 on 2023-04-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationvo',
            name='import_href',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hatdetails',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatdetails', to='hats_rest.locationvo'),
        ),
    ]
